// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateMySQL(arg1) {
  return window['go']['main']['App']['CreateMySQL'](arg1);
}

export function DeleteContainer(arg1) {
  return window['go']['main']['App']['DeleteContainer'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListContainers() {
  return window['go']['main']['App']['ListContainers']();
}

export function RestartContainer(arg1) {
  return window['go']['main']['App']['RestartContainer'](arg1);
}

export function StartContainer(arg1) {
  return window['go']['main']['App']['StartContainer'](arg1);
}

export function StopContainer(arg1) {
  return window['go']['main']['App']['StopContainer'](arg1);
}
