// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';

export function CreateMySQL(arg1:database.MySQLConfig):Promise<void>;

export function DeleteContainer(arg1:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function ListContainers():Promise<Array<database.Container>>;

export function RestartContainer(arg1:string):Promise<void>;

export function StartContainer(arg1:string):Promise<void>;

export function StopContainer(arg1:string):Promise<void>;
